apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::317831786916:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-13Q4LU6IJ9WKS
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::317831786916:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-24T15:24:00Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:mapRoles: {}
      manager: vpcLambda
      operation: Update
      time: "2022-07-24T15:24:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1578"
  uid: 156c2f64-bd98-468c-aad0-c3a9dbf454e2
