apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::317831786916:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-105WLLK05DC60
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::317831786916:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-23T14:36:35Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data: {}
      manager: vpcLambda
      operation: Update
      time: "2022-07-23T14:36:35Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:mapRoles: {}
      manager: kubectl-patch
      operation: Update
      time: "2022-07-23T15:14:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "7998"
  uid: 96dbf8db-4a07-44c2-943d-e5b506dd0d3f
